Repository razrabs-media/journal, pull requests merged in 2022-08, with the labels that each got.

#364 Добавлена поддержка Sitemap
  package.json
  public/robots.txt
  public/sitemap.xml
  src/pages/_app.tsx
  src/pages/feeds/[uid]/sitemap.xml/index.tsx
  src/pages/feeds/sitemap.xml/index.tsx
  src/shared/lib/helmet/index.tsx
  src/shared/lib/host/getHost.ts
  src/shared/lib/host/index.ts
  src/shared/lib/index.ts
  src/shared/ui/footer/index.tsx
  yarn.lock
Labels: feature, dependencies

#273 RAZ: hide keyboard
  .env
  .env.development
  src/widgets/comments/ui/input/index.tsx
Labels: ux

#417 feat: code blocks theme switching
  src/shared/ui/markdown-renderer/index.tsx
  src/shared/ui/markdown-renderer/theme.ts
Labels: bug

#460 Правка опечатки в карточке организации
  src/shared/lib/helmet/index.tsx
Labels: high
